import type { Metadata } from 'next'
import './globals.css'
import Header from './components/Header'
import Provider from './Provider'

export const metadata: Metadata = {
  title: 'Pinterest Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <Header />
          {children}
        </Provider>
      </body>
    </html>
  )
}
